=== ericmoros/Desarrollo-web/Lenguajes marcas/Evaluación - 2/Trabajo/phone-towers/antena-telefonia.dtd
<!ELEMENT resultado (totalCount, start, rows, result)>
<!ELEMENT totalCount (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT result (antena+)>
<!ELEMENT antena (hojaPgou, numAntenaPlano, numAntenaPi?, id, numero, calle, idOperadora, pubDate?, codEmplazamiento?, coordenadaSin?, lastUpdated?, relimplantacion, description, geometry, icon)>
<!ELEMENT hojaPgou (#PCDATA)>
<!ELEMENT numAntenaPlano (#PCDATA)>
<!ELEMENT numAntenaPi (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT idOperadora (operadora_antena)>
<!ELEMENT operadora_antena (id, title, descripcion, pubDate)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT pubDate (#PCDATA)>
<!ELEMENT codEmplazamiento (#PCDATA)>
<!ELEMENT coordenadaSin (#PCDATA)>
<!ELEMENT lastUpdated (#PCDATA)>
<!ELEMENT relimplantacion (implantacion-antena)>
<!ELEMENT implantacion-antena (id, numExp, tipoPleno, lastUpdated)>
<!ELEMENT numExp (#PCDATA)>
<!ELEMENT tipoPleno (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT geometry (type, coordinates)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT coordinates (#PCDATA)>
<!ELEMENT icon (#PCDATA)>

=== ericmoros/Desarrollo-web/Lenguajes marcas/Evaluación - 2/Trabajo/phone-towers/antena-telefonia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultado SYSTEM "antena-telefonia.dtd">
<resultado>
  <totalCount>231</totalCount>
  <start>0</start>
  <rows>50</rows>
  <result>
    <antena>
      <hojaPgou>K-16</hojaPgou>
      <numAntenaPlano>44</numAntenaPlano>
      <numAntenaPi>66</numAntenaPi>
      <id>316</id>
      <numero>9</numero>
      <calle>Madre Genoveva Torres Morales</calle>
      <idOperadora>
        <operadora_antena>
          <id>4</id>
          <title>Vodafone</title>
          <descripcion>Vodafone</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <lastUpdated>2011-05-23T22:00:00Z</lastUpdated>
      <relimplantacion>
        <implantacion-antena>
          <id>66</id>
          <numExp>866848/2005</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Vodafone</li><li>Dirección: Madre Genoveva Torres Morales 9</li><li>Fecha de Aprobación: 27-07-2006</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>675912.15,4612280.72</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Vodafone.gif</icon>
    </antena>
    <antena>
      <hojaPgou>M-24</hojaPgou>
      <numAntenaPlano>115</numAntenaPlano>
      <id>392</id>
      <numero>nº80. C1-12-34-35-36</numero>
      <calle>Azufre</calle>
      <idOperadora>
        <operadora_antena>
          <id>4</id>
          <title>Vodafone</title>
          <descripcion>Vodafone</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <pubDate>2013-01-20T23:00:00Z</pubDate>
      <codEmplazamiento>0196ZX_AT_Z_PLG_RECICLADO</codEmplazamiento>
      <coordenadaSin>     00º 50¿40¿ W       41º 34¿4¿ N</coordenadaSin>
      <relimplantacion>
        <implantacion-antena>
          <id>112</id>
          <numExp>456226/2010</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
          <lastUpdated>2012-04-10T22:00:00Z</lastUpdated>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Vodafone</li><li>Dirección: Azufre nº80. C1-12-34-35-36</li><li>Fecha de Aprobación: 26-03-2012</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>679734.28,4604113.67</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Vodafone.gif</icon>
    </antena>
    <antena>
      <hojaPgou>M-12</hojaPgou>
      <numAntenaPlano>2</numAntenaPlano>
      <id>394</id>
      <numero>18-20 </numero>
      <calle>Avda, Santa Isabel</calle>
      <observaciones>Finalizar sin sanción en exp. 1350074/2009 el 21/01/2010</observaciones>
      <idOperadora>
        <operadora_antena>
          <id>5</id>
          <title>Xfera</title>
          <descripcion>Xfera</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <lastUpdated>2014-07-01T22:00:00Z</lastUpdated>
      <pubDate>2015-10-28T23:00:00Z</pubDate>
      <relimplantacion>
        <implantacion-antena>
          <id>113</id>
          <numExp>962956/2007</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Xfera</li><li>Dirección: Avda, Santa Isabel 18-20 </li><li>Fecha de Aprobación: 29-05-2009</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>679978.29,4615576.01</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Xfera.gif</icon>
    </antena>
    <antena>
      <hojaPgou>K-15</hojaPgou>
      <numAntenaPlano>4</numAntenaPlano>
      <id>396</id>
      <numero>13</numero>
      <calle>Cesar Augusto (Hotel Melia)</calle>
      <idOperadora>
        <operadora_antena>
          <id>5</id>
          <title>Xfera</title>
          <descripcion>Xfera</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <lastUpdated>2011-06-08T22:00:00Z</lastUpdated>
      <pubDate>2013-01-20T23:00:00Z</pubDate>
      <codEmplazamiento>1B2Z0038</codEmplazamiento>
      <coordenadaSin>00º53¿04,50"W 41º39¿10,70"N</coordenadaSin>
      <relimplantacion>
        <implantacion-antena>
          <id>421</id>
          <numExp>856851/2010</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
          <lastUpdated>2012-04-10T22:00:00Z</lastUpdated>
          <pubDate>2011-04-13T22:00:00Z</pubDate>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Xfera</li><li>Dirección: Cesar Augusto (Hotel Melia) 13</li><li>Fecha de Aprobación: 26-03-2012</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>676155.2,4613490.31</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Xfera.gif</icon>
    </antena>
    <antena>
      <hojaPgou>47</hojaPgou>
      <numAntenaPlano>6</numAntenaPlano>
      <id>398</id>
      <numero> parcela-1, 105 </numero>
      <calle>Carretera de Madrid</calle>
      <idOperadora>
        <operadora_antena>
          <id>5</id>
          <title>Xfera</title>
          <descripcion>Xfera</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <lastUpdated>2014-07-01T22:00:00Z</lastUpdated>
      <pubDate>2015-10-28T23:00:00Z</pubDate>
      <relimplantacion>
        <implantacion-antena>
          <id>113</id>
          <numExp>962956/2007</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Xfera</li><li>Dirección: Carretera de Madrid  parcela-1, 105 </li><li>Fecha de Aprobación: 29-05-2009</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>676170.73,4615122.14</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Xfera.gif</icon>
    </antena>
    <antena>
      <hojaPgou>K-14</hojaPgou>
      <numAntenaPlano>7</numAntenaPlano>
      <id>399</id>
      <numero> nº 100</numero>
      <calle>Conde Aranda</calle>
      <idOperadora>
        <operadora_antena>
          <id>5</id>
          <title>Xfera</title>
          <descripcion>Xfera</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <pubDate>2013-01-20T23:00:00Z</pubDate>
      <relimplantacion>
        <implantacion-antena>
          <id>113</id>
          <numExp>962956/2007</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Xfera</li><li>Dirección: Conde Aranda  nº 100</li><li>Fecha de Aprobación: 29-05-2009</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>675797.3,4613910.46</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Xfera.gif</icon>
    </antena>
    <antena>
      <hojaPgou>K-15</hojaPgou>
      <numAntenaPlano>8</numAntenaPlano>
      <id>400</id>
      <numero>17</numero>
      <calle>Gran Vía</calle>
      <idOperadora>
        <operadora_antena>
          <id>5</id>
          <title>Xfera</title>
          <descripcion>Xfera</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <lastUpdated>2015-08-31T22:00:00Z</lastUpdated>
      <relimplantacion>
        <implantacion-antena>
          <id>113</id>
          <numExp>962956/2007</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Xfera</li><li>Dirección: Gran Vía 17</li><li>Fecha de Aprobación: 29-05-2009</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>675989.18,4612822.15</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Xfera.gif</icon>
    </antena>
    <antena>
      <hojaPgou>H-16</hojaPgou>
      <numAntenaPlano>9</numAntenaPlano>
      <id>401</id>
      <numero>10</numero>
      <calle>Las Pléyades</calle>
      <idOperadora>
        <operadora_antena>
          <id>5</id>
          <title>Xfera</title>
          <descripcion>Xfera</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
      <relimplantacion>
        <implantacion-antena>
          <id>114</id>
          <numExp>1250833/2006</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
        </implantacion-antena>
        <implantacion-antena>
          <id>113</id>
          <numExp>962956/2007</numExp>
          <tipoPleno>Pleno inclusión</tipoPleno>
        </implantacion-antena>
      </relimplantacion>
      <description><![CDATA[<ul><li>Operadora: Xfera</li><li>Dirección: Las Pléyades 10</li><li>Fecha de Aprobación: 29-05-2009</li><li>Fecha de Aprobación: 29-05-2009</li></ul>]]></description>
      <geometry>
        <type>Point</type>
        <coordinates>672142.24,4612000.91</coordinates>
      </geometry>
      <icon>https://www.zaragoza.es/cont/paginas/img/antenas/Xfera.gif</icon>
    </antena>
    <antena>
      <hojaPgou>M-12</hojaPgou>
      <numAntenaPlano>11</numAntenaPlano>
      <id>403</id>
      <numero> n º 32</numero>
      <calle>Santo Domingo, Isabel de</calle>
      <idOperadora>
        <operadora_antena>
          <id>5</id>
          <title>Xfera</title>
          <descripcion>Xfera</descripcion>
          <pubDate>2009-08-30T22:00:00Z</pubDate>
        </operadora_antena>
      </idOperadora>
