=== ericmoros/Desarrollo-web/1/Lenguajes marcas/Evaluación - 2/Tareas/dtd/Avanzado/4/personas.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,nacimiento?,direccion,(mujer|varon))>
<!ELEMENT nombre EMPTY>
<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento
  anyo CDATA #REQUIRED
  dia CDATA #REQUIRED
  mes NMTOKEN #REQUIRED>
<!ELEMENT direccion (calle,poblacion,provincia,cpostal)>
<!ELEMENT mujer EMPTY>
<!ELEMENT varon EMPTY>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>

=== ericmoros/Desarrollo-web/Lenguajes marcas/Evaluación - 2/Tareas/dtd/Avanzado/Ejercicio DTD avanzado 4. Creación de un XML y un DTD a partir de un esquema/personas.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
  <persona>
    <nombre></nombre>
    <nacimiento dia="10" mes="Abril" anyo="1982"/>
    <direccion>
      <calle>caoba, 1</calle>
      <poblacion>Madrid</poblacion>
      <provincia>Madrid</provincia>
      <cpostal>28005</cpostal>
    </direccion>
    <varon/>
  </persona>
  <persona>
    <nombre></nombre>
    <direccion>
      <calle>caoba, 1</calle>
      <poblacion>Madrid</poblacion>
      <provincia>Madrid</provincia>
      <cpostal>28005</cpostal>
    </direccion>
    <mujer/>
  </persona>
</personas>
