=== ericmoros/Desarrollo-web/Lenguajes marcas/Evaluación - 2/Examen/Ej3/ejercicio03.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://w3schools.com"
           xmlns="https://w3schools.com"
           elementFormDefault="qualified">
<xs:element name="libro">
  <xs:complexType>
  <xs:sequence>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="autor" type="xs:string"/>
    <xs:element name="personaje" minOccurs="0" maxOccurs="unbounded">
      <xs:complexType>
      <xs:sequence>
          <xs:element name="nombre" type="xs:string"/>
          <xs:element name="amigo" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="desde" type="xs:date"/>
       <xs:element name="calificacion" type="xs:string"/>
      </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="isbn" type="xs:string"/>
  </xs:complexType>
</xs:element>
</xs:schema>

=== ericmoros/Desarrollo-web/1/Lenguajes marcas/Evaluación - 2/Examen/Ej3/ejercicio03.xml
<?xml version="1.0" encoding="utf-8"?>
<libro xmlns="https://w3schools.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="ejercicio03.xsd" isbn="abcde">
  <titulo>Mi libro</titulo>
  <autor>Eric Moros Pérez</autor>
  <personaje>
    <nombre>Smith</nombre>
    <desde>1999-01-02</desde>
    <calificacion>Bueno</calificacion>
  </personaje>
  <personaje>
    <nombre>Víctor</nombre>
    <amigo>Eric</amigo>
    <desde>2011-01-01</desde>
    <calificacion>El mejor</calificacion>
  </personaje>
</libro>
