=== ericmoros/Desarrollo-web/Lenguajes marcas/Evaluación - 2/Tareas/xsd/Avanzado/1/docencia.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://w3schools.com"
           xmlns="https://w3schools.com"
           elementFormDefault="qualified">
  <xs:element name="docencia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="grupo" type="xs:string" />
        <xs:element name="asignatura">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="horas">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="hora" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="time" use="required" type="xs:time" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="profesor" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ericmoros/Desarrollo-web/Lenguajes marcas/Evaluación - 2/Tareas/xsd/Avanzado/1/docencia.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<docencia xmlns="https://w3schools.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="docencia.xsd">
  <grupo>1ASIR</grupo>
  <asignatura>
    <nombre></nombre>
    <horas>
      <hora time="22:50:00" />
      <hora time="23:50:00" />
    </horas>
    <profesor></profesor>
  </asignatura>
</docencia>
