=== ericmoros/Desarrollo-web/1/Lenguajes marcas/Evaluación - 2/Tareas/dtd/Básico/21/ventas.dtd
<!ELEMENT ventas (empresa)>
<!ELEMENT empresa (nombre,informes)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT informes (informe)>
<!ELEMENT informe (descripcion,zona)>
<!ATTLIST informe
  id    CDATA   #REQUIRED
  tipo  NMTOKEN #REQUIRED
  fecha CDATA   #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT zona (norte,centro,sur)>
<!ELEMENT norte (trimestre)+>
<!ELEMENT centro (trimestre)+>
<!ELEMENT sur (trimestre)+>
<!ELEMENT trimestre (#PCDATA)>
<!ATTLIST trimestre
  numero (1|2|3|4) #REQUIRED
  default (NO_INFO) #REQUIRED
  numero CDATA #REQUIRED>

=== ericmoros/Desarrollo-web/Lenguajes marcas/Evaluación - 2/Tareas/dtd/Básico/Ejercicio DTD Básico 21. Obtener XML y DTD de unos datos y requisitos/ventas.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ventas SYSTEM "ventas.dtd">
<ventas>
  <empresa>
    <nombre>Ediciones Aranda Informe regional del ventas</nombre>
    <informes>
      <informe id="1" tipo="libro" fecha="30/12/2016">
        <descripcion>informe de ventas para las regiones Norte, Centro y Sur</descripcion>
        <zona>
          <norte>
            <trimestre numero="1" default="NO_INFO">24000</trimestre>
            <trimestre numero="2" default="NO_INFO">38600</trimestre>
            <trimestre numero="3" default="NO_INFO"></trimestre>
            <trimestre numero="4" default="NO_INFO"></trimestre>
          </norte>
          <centro>
            <trimestre numero="1" default="NO_INFO"></trimestre>
            <trimestre numero="2" default="NO_INFO">16080</trimestre>
            <trimestre numero="3" default="NO_INFO">25000</trimestre>
            <trimestre numero="4" default="NO_INFO">29000</trimestre>
          </centro>
          <sur>
            <trimestre numero="1" default="NO_INFO">27000</trimestre>
            <trimestre numero="2" default="NO_INFO">31400</trimestre>
            <trimestre numero="3" default="NO_INFO">40100</trimestre>
            <trimestre numero="4" default="NO_INFO">30000</trimestre>
          </sur>
        </zona>
      </informe>
    </informes>
  </empresa>
</ventas>
